services:
  # База данных
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pirate_db
      POSTGRES_USER: pirate_user
      POSTGRES_PASSWORD: pirate_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pirate_user" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

  # Веб-приложение Django
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    restart: unless-stopped

  # Celery Worker
  worker:
    build: .
    env_file:
      - .env
    command: celery -A noob worker -l info
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - media_volume:/app/media
    restart: unless-stopped

  # Celery Beat
  beat:
    build: .
    env_file:
      - .env
    command: celery -A noob beat -l info
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  # Flower
  flower:
    build:
      context: .
      dockerfile: Dockerfile.flower
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - worker
    restart: unless-stopped


volumes:
  postgres_data:
  static_volume:
  media_volume: